### ISSUE TITLE
Disabling check reg in aamod_norm_write

### ISSUE THREAD

**Issue by TamerGezici** [automaticanalysis/automaticanalysis#379] opened 2023-03-25 08:01 UTC
https://github.com/automaticanalysis/automaticanalysis/blob/f7849b18297c277e3603e06e35010a437520d2eb/aa_modules/aamod_norm_write.m#L166

How can I disable check reg here? For 3D NIfTI, it tries running it for all volumes one by one. Would be better if it did it for one volume? Maybe the middle one?

 I had tried disabling it months before by trying to dissatisfy the if block above, but I could not figure out how. So I had decided to comment it out as a temp. measure.

Thanks.

**Comment by tiborauer** [comment] 2023-03-25 08:07
`aap.tasksettings.aamor_norm_write.diagnostics = 0;` should work.

(and you should use 4D NIfTI 😉)

**Comment by TamerGezici** [comment] 2023-03-25 09:31
> `aap.tasksettings.aamor_norm_write.diagnostics = 0;` should work.
I think that was indeed what I tried. I will try again and let you know.

> (and you should use 4D NIfTI 😉)

Can't teach an old a new trick. If I had high computational power and large clusters with tons of GB's of RAM, I would not hesitate to switch. But running analysis on a personal laptop has it's toll, and right now I can not do much about it.

**Comment by tiborauer** [comment] 2023-03-25 09:38
I think 4D NIfTI is better in terms of resource management, so it should be beneficial in lower-spec systems. Is not that what you experience?

**Comment by TamerGezici** [comment] 2023-03-25 09:55
> I think 4D NIfTI is better in terms of resource management, so it should be beneficial in lower-spec systems. Is not that what you experience?

I have found that whenever I run an aa pipeline on 4D data, the analysis takes much much longer compared to 3D.

**Comment by tiborauer** [comment] 2023-03-25 10:13
Interesting!  I have no issuse using 4D NIfTI on desktop PC or laptop.

Copying should definitely be faster because copying/linking one file is always faster, not even mentioning retrieving and putting file(s) into the streams.
The only steps where using 4D NIfTI is expected to be much slower are when you convert from DICOM or import from NIfTI due to the extra step of merging.

I wonder whether it must be due to (inefficient) antivirus, which scans the whole 4D NIfTI file whenever you access even a single volume or slice (from functions). I am using vanilla Microsoft Defender without any issue.

**Comment by TamerGezici** [comment] 2023-03-25 10:33
AV issue sounds plausible. I will test this.

**Comment by TamerGezici** [comment] 2023-03-25 12:07
> `aap.tasksettings.aamor_norm_write.diagnostics = 0;` should work.

There were some typos here:

`aap.tasksettings.aamod_norm_write.diagnostic = 0;`

I fixed them. It may be worth updating your original post :)

**Comment by TamerGezici** [comment] 2023-03-25 12:17
I disabled my antivirus (not uninstall, but disabled it through its own options) and ran the analysis again.

Single subject, single run.

Computer specs: 2018 gaming laptop, SSD, 16GB RAM. 2.5ghz i7 8750H processor.
Did not use parallel computing toolbox.

3D was done in 10 minutes, 4D was done in 16 minutes.

3D epifromnifti Elapsed time = 0h:0m:6s
4D epifromnifti Elapsed time = 0h:0m:59s

3D smoothing -- Elapsed time = 0h:1m:19s
4D smoothing -- Elapsed time = 0h:3m:57s

3D realign -- Elapsed time = 0h:0m:48s
4D realign -- Elapsed time = 0h:3m:11s

It does seem to be faster for normalization:

3D normalization -- Elapsed time = 0h:1m:58s
4D normalization --  Elapsed time = 0h:1m:32s

Full console outputs:

4D NIfTI:

https://gist.github.com/TamerGezici/73e7b95f1e926a4863c1c4788099a3f3

3D NIfTI:

https://gist.github.com/TamerGezici/6b0f23822d0c31bdb328b36ec25c4c2a

**Comment by tiborauer** [comment] 2023-03-25 12:29
You have a decent laptop, similar to mine. :)

I think the difference in normalisation is negligible unless consistent across several iterations.

The difference in epifromnifti is expected as I described above.

The differences in realign and smoothing indicate that the issue is likely in the SPM functions.

You can perhaps post it on the SPM mailing list to see whether it is a common experience and someone has an explanation for it.

**Comment by tiborauer** [comment] 2023-03-25 12:29
Thank you for the testing!

**Comment by TamerGezici** [comment] 2023-03-25 12:40
> You have a decent laptop, similar to mine. :)

Thanks :)

> I think the difference in normalisation is negligible unless consistent across several iterations.
> 
> The difference in epifromnifti is expected as I described above.

What is what you refer to as "merging"? What is merged here?

> The differences in realign and smoothing indicate that the issue is likely in the SPM functions.
> 
> You can perhaps post it on the SPM mailing list to see whether it is a common experience and someone has an explanation for it.

Depending on your answer, I was thinking of asking if I should do this.

The thing is I guess they'll want me to try it on GUI, rather than AA. I kinda don't like using GUI.

**Comment by tiborauer** [comment] 2023-03-25 12:53
> What is what you refer to as "merging"? What is merged here?

Yes. The 3D NIfTI volumes into 4D NIfTI.

> The thing is I guess they'll want me to try it on GUI, rather than AA. I kinda don't like using GUI.

I do not think the GUI would make any difference. A more targeted test would be to put `tic` and `toc` functions around the SPM functions in the module(s). This would eliminate any confounds due to aa or the GUI.

**Comment by TamerGezici** [comment] 2023-03-25 14:11
> > What is what you refer to as "merging"? What is merged here?
> Yes. The 3D NIfTI volumes into 4D NIfTI.

Well, but my volumes were already 4D. I converted them using dcm2niix.

![image](https://user-images.githubusercontent.com/11014942/227722339-bf893b46-8d7f-464c-89ea-c30b26a0737c.png)

So, why would epifromnifti take so long then?

**Comment by tiborauer** [comment] 2023-03-25 14:32
If you look at the code, you will see: (4D) volumes are split to remove the dummy scans and re-merged into 4D without them.

**Closed** 2023-08-03 09:39 UTC
